name = "Xsum"
uuid = "1fd64df0-a4d2-11e9-360d-2f03868f4cf5"
version = "1.2.0"

[deps]
xsum_jll = "e979a739-315a-50ee-b437-b496a9503be1"

[compat]
julia = "1.3"
xsum_jll = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]